apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
  namespace: three-tier
  labels: 
    role: api
    env: demo
spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: api
        image: 842945290089.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
        imagePullPolicy: Always
        env:
          - name: DB_CONNECTION
            value: mysql
          - name: DB_HOST
            value: mysql-svc  # Update this if your MySQL service has a different name
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            value: laravel_db
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-sec
                key: password
        ports:
        - containerPort: 8000
        livenessProbe: 
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
