apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: three-tier
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql  # Changed from /data/postgres to /data/mysql
