apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
  name: mysql-svc
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: LoadBalancer  # Use ClusterIP unless you specifically need external access
